### PR TITLE
Handle negative values for free space

### PR DESCRIPTION
**Pull request by conkiztador**
Hi, thanks for creating this project! 👍 

In situations where the free space of the data store is unknown (using
an S3 backend for example), an enum value can be returned that is represented
by a negative integer:

    const SPACE_NOT_COMPUTED = -1;
    const SPACE_UNKNOWN = -2;
    const SPACE_UNLIMITED = -3;

Example:

    <data>
      <nextcloud>
        <system>
        <freespace>-2</freespace>

This changes the free space data types to signed integer to handle this.
The value isn't particularly useful, but this at least avoids the XML parser
dying with a strconv.ParseUint error.

### CODE REVIEW

**Comment by xperimental** [comment]
Hi. Sorry for the delay.

> Hi, thanks for creating this project! +1

You're welcome. :sunny: 

I have updated the branch with a few changes, please have a look if that sounds okay for you:

- Moved test data to special `testdata` directory (this directory is not considered a package by the Go toolchain)
- Moved the parse function to the `serverinfo` package. I think it fits better there.
- Refactored the test, so that it looks "more Go". This was purely cosmetic, but I like to keep them looking _similar_. :lipstick: 

Another thought was that if the metric should not get reported with negative space remaining, but maybe some other "flag" metrics should be set to `1` instead. What do you think?

**Comment by conkiztador** [comment]
> Hi. Sorry for the delay.
> 
> > Hi, thanks for creating this project! +1
> 
> You're welcome. ☀️
> 
> I have updated the branch with a few changes, please have a look if that sounds okay for you:
> 
> * Moved test data to special `testdata` directory (this directory is not considered a package by the Go toolchain)
> * Moved the parse function to the `serverinfo` package. I think it fits better there.
> * Refactored the test, so that it looks "more Go". This was purely cosmetic, but I like to keep them looking _similar_. 💄

All looks good to me. Thanks for improving it!

> 
> Another thought was that if the metric should not get reported with negative space remaining, but maybe some other "flag" metrics should be set to `1` instead. What do you think?

That would also be fine (and probably makes more sense semantically). The value isn't useful to me so I don't have a strong opinion either way.

**Comment by xperimental** [comment]
> That would also be fine (and probably makes more sense semantically). The value isn't useful to me so I don't have a strong opinion either way.

Ok, then I'll squash&merge it as it is to master and then think about this separately.

**Comment by conkiztador** [comment]
Thanks @xperimental!

**Pull request merged**
